[theme]
base="dark"
primaryColor="#1DB954"       # Spotify green style (you can change)
backgroundColor="#0E1117"    # Dark background
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"
